import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bgImg`}
      >
        <div className="blob-container">
          <svg
            viewBox="0 0 200 200"
            xmlns="http://www.w3.org/2000/svg"
            className="blob1"
          >
            <path
              className="blob1"
              fill="#F2F4F8"
              d="M38.2,-38.9C51.9,-34.1,66.8,-24.3,71.4,-10.7C76,2.8,70.4,20.1,61.3,35C52.2,49.8,39.7,62.3,26.7,62.2C13.7,62.1,0.2,49.3,-13.2,41.9C-26.6,34.6,-39.9,32.7,-46.8,25C-53.8,17.3,-54.3,3.8,-55.1,-12.9C-55.9,-29.6,-57.1,-49.5,-47.9,-55C-38.8,-60.5,-19.4,-51.7,-3.5,-47.5C12.3,-43.3,24.6,-43.7,38.2,-38.9Z"
              transform="translate(100 100)"
            />
          </svg>

          <svg
            viewBox="0 0 200 200"
            xmlns="http://www.w3.org/2000/svg"
            className="blob2"
          >
            <path
              fill="#F2F4F8"
              d="M35,-25.2C42.8,-18.2,44.6,-3.8,41.9,10.1C39.1,24,31.8,37.5,21,42.1C10.2,46.8,-4.2,42.7,-14.7,35.6C-25.2,28.6,-31.9,18.7,-34.2,8C-36.6,-2.8,-34.6,-14.4,-28.2,-21C-21.7,-27.7,-10.9,-29.4,1.4,-30.5C13.6,-31.6,27.3,-32.1,35,-25.2Z"
              transform="translate(100 100)"
            />
          </svg>

          <svg
            viewBox="0 0 200 200"
            xmlns="http://www.w3.org/2000/svg"
            className="blob3"
          >
            <path
              fill="#F2F4F8"
              d="M45.5,-31.1C56.7,-22.2,62.1,-3.4,56.4,9.5C50.8,22.3,34.1,29.2,22,28.2C10,27.3,2.7,18.5,-10.9,14.9C-24.5,11.4,-44.3,13,-51.9,4.7C-59.5,-3.6,-54.8,-21.8,-44.2,-30.6C-33.5,-39.4,-16.7,-38.8,0.2,-39C17.1,-39.1,34.2,-40,45.5,-31.1Z"
              transform="translate(100 100)"
            />
          </svg>

          <svg
            viewBox="0 0 200 200"
            xmlns="http://www.w3.org/2000/svg"
            className="blob4"
          >
            <path
              fill="#BAE6FF"
              d="M16.1,-10.7C24.1,-2.8,36.2,4.1,40.4,18.7C44.7,33.4,41.1,55.7,28.8,62.9C16.4,70,-4.8,62,-21.3,51.3C-37.9,40.6,-49.9,27.4,-58.3,8.2C-66.8,-10.9,-71.6,-36,-61.3,-44.4C-51,-52.9,-25.5,-44.8,-10.7,-36.2C4,-27.7,8.1,-18.7,16.1,-10.7Z"
              transform="translate(100 100)"
            />
          </svg>

          <svg
            viewBox="0 0 200 200"
            xmlns="http://www.w3.org/2000/svg"
            className="blob5"
          >
            <path
              fill="#BAE6FF"
              d="M58.2,-44.8C72.5,-28.5,79.1,-4.5,74.3,17.2C69.5,38.8,53.3,58,34.1,65.1C14.8,72.3,-7.7,67.4,-25.3,57.1C-42.9,46.8,-55.8,31.3,-59,14.2C-62.3,-2.8,-56.1,-21.3,-44.6,-36.9C-33.2,-52.5,-16.6,-65.3,2.7,-67.4C22,-69.6,43.9,-61.1,58.2,-44.8Z"
              transform="translate(100 100)"
            />
          </svg>

          <svg
            viewBox="0 0 200 200"
            xmlns="http://www.w3.org/2000/svg"
            className="blob7"
          >
            <path
              fill="#F2F4F8"
              d="M41,-45.5C54.9,-37.2,69.2,-26,72,-12.3C74.9,1.3,66.2,17.3,55.2,27.6C44.1,37.9,30.7,42.6,15.5,52.3C0.3,62.1,-16.5,76.9,-30,75.2C-43.5,73.5,-53.6,55.1,-60.3,37.6C-67,20.2,-70.4,3.6,-68.3,-12.6C-66.1,-28.9,-58.5,-44.7,-46.2,-53.3C-33.9,-61.9,-16.9,-63.3,-1.7,-61.3C13.5,-59.2,27.1,-53.8,41,-45.5Z"
              transform="translate(100 100)"
            />
          </svg>
        </div>

        <div className="z-20 relative">
          <AuthProvider>{children}</AuthProvider>
        </div>
      </body>
    </html>
  );
}
